version: "3"
services:
  gateway: 
    image: nginx:latest
    restart: on-failure
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./run_env/log:/var/log/nginx
    ports: 
      - 5040:80
    extra_hosts:
      - "host.docker.internal:host-gateway"


